name = "Solstice"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56b1ffd16f8980a7f7bb236faaf3fc07932856d28bae621c1df29f70da082119"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "resources/datapack"
