name = "Solstice"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a85228cb97f53be6d68a4e13f0a64887363df7c47f0a6327b8012b95fbcabf57"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "resources/datapack"
