name = "Solstice"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dd2bcda501b4a624c0bb47ae9ccf3b090e0745573719a02efde6920231abacc"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "resources/datapack"
